### ISSUE TITLE
Fix error occurring upon a player joining the server.

### ISSUE THREAD

**Issue by w15736776759** [Dans-Plugins/Fiefs#113]
[16:46:55 ERROR]: Could not pass event PlayerJoinEvent to Fiefs v0.10
java.lang.NullPointerException: Cannot invoke "dansplugins.factionsystem.MedievalFactions.getConfig()" because the return value of "dansplugins.factionsystem.MedievalFactions.getInstance()" is null
        at dansplugins.factionsystem.eventhandlers.JoinHandler.createPowerRecordForPlayer(JoinHandler.java:90) ~[Fiefs-0.10(1).jar:?]
        at dansplugins.factionsystem.eventhandlers.JoinHandler.createRecordsForPlayer(JoinHandler.java:76) ~[Fiefs-0.10(1).jar:?]
        at dansplugins.factionsystem.eventhandlers.JoinHandler.handle(JoinHandler.java:37) ~[Fiefs-0.10(1).jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor417.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:git-Purpur-1606]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:631) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.players.PlayerList.postChunkLoadJoin(PlayerList.java:363) ~[purpur-1.18.2.jar:git-Purpur-1606]
        at net.minecraft.server.players.PlayerList.lambda$placeNewPlayer$1(PlayerList.java:305) ~[purpur-1.18.2.jar:git-Purpur-1606]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.tick(ServerGamePacketListenerImpl.java:320) ~[?:?]
        at net.minecraft.network.Connection.tick(Connection.java:576) ~[?:?]
        at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:201) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1648) ~[purpur-1.18.2.jar:git-Purpur-1606]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:522) ~[purpur-1.18.2.jar:git-Purpur-1606]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1482) ~[purpur-1.18.2.jar:git-Purpur-1606]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1246) ~[purpur-1.18.2.jar:git-Purpur-1606]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:320) ~[purpur-1.18.2.jar:git-Purpur-1606]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by dmccoystephenson** [comment]
Closing this since we're rewriting the plugin.
